linters:
  enable:
    - gofmt
    - golint
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - scopelint
run:
  skip-dirs:
    - modelplugin

issues:
  exclude-rules:
    - path: pkg/northbound/gnmi/set.go
      linters:
        - typecheck
    - path: cmd/onos-e2t.go
      linters:
        - depguard
